name: smile_app
description: Smile App - Tu espacio a tu ritmo.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.5.1
  google_fonts: ^6.2.1
  supabase_flutter: ^2.0.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.3.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - lib/assets/
